insert into mst_function(function_id,function_name,function_path,function_comment,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('EMP0001DTL','社員詳細','/Emp0001Dtl/init','社員の詳細および更新','0',null,null,null,null,null,null);
insert into mst_function(function_id,function_name,function_path,function_comment,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('EMP0001LST','社員一覧','/Emp0001Lst/init','社員の一覧およびCSV出力','0',null,null,null,null,null,null);
insert into mst_function(function_id,function_name,function_path,function_comment,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('EMP0001UPL','社員CSVアップロード','/Emp0001Upl/init','社員のCSV一括登録','0',null,null,null,null,null,null);

insert into authorized_user(user_id,user_password,last_update_ymd,last_update_password,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('root','root','root',null,'0',null,null,null,null,null,null);

insert into mst_menu(hierarchy_id,function_order,function_id,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('mst/emp/lst',0,'EMP0001LST','0',null,null,null,null,null,null);
insert into mst_menu(hierarchy_id,function_order,function_id,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('mst/emp/upl',1,'EMP0001UPL','0',null,null,null,null,null,null);

insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('0000001','テスト太郎','19900101','1','','','19000101','','','0','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00001','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00002','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00003','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00004','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00005','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00006','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00007','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00008','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00009','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00010','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00011','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00012','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00013','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00014','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00015','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00016','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00017','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('00018','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('11111','12345','20190101','1',null,null,null,null,null,'1','0',null,null,null,null,null,null);
insert into mst_employee(employee_id,employee_name,birth_ymd,sex,zip_code,address,joined_ymd,retire_ymd,department_id,authorized,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('12345','12345','20190101','1','','','','','','1','0',null,null,null,null,null,null);

insert into mst_department(department_id,department_name,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('001','第一事業部','0',null,null,null,null,null,null);
insert into mst_department(department_id,department_name,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('002','第二事業部','0',null,null,null,null,null,null);
insert into mst_department(department_id,department_name,delete_flg,create_module_id,create_user_id,create_ymd,update_module_id,update_user_id,update_ymd) values ('003','第三事業部','0',null,null,null,null,null,null);